# Generated by Django 3.1.5 on 2021-01-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shipment',
            table='shipments',
        ),
    ]
